// BOOK CREATE UPDATE
export const REQUEST_UPDATE_BOOK = 'REQUEST_UPDATE_BOOK';
export const RECEIVE_UPDATE_BOOK = 'RECEIVE_UPDATE_BOOK';
export const ERROR_RECEIVE_UPDATE_BOOK = 'ERROR_RECEIVE_UPDATE_BOOK';

export const REQUEST_CREATE_BOOK = 'REQUEST_CREATE_BOOK';
export const RECEIVE_CREATE_BOOK = 'RECEIVE_CREATE_BOOK';
export const ERROR_RECEIVE_CREATE_BOOK = 'ERROR_RECEIVE_CREATE_BOOK';

export const REQUEST_GET_BOOK = 'REQUEST_GET_BOOK';
export const RECEIVE_GET_BOOK = 'RECEIVE_GET_BOOK';
export const ERROR_RECEIVE_GET_BOOK = 'ERROR_RECEIVE_GET_BOOK';

export const TO_INITIAL = 'TO_INITIAL';

